#!/usr/bin/env python3
"""
WAF Detector - AlZill V6 Pro
Advanced WAF/IPS detection with cache bypass, multi-vector testing, cookie fingerprinting
Features: Cache bypass | Headers | Cookies | Response Body | Status Codes | Multi-payload
"""

import requests
import re
import time
import random
from termcolor import cprint
from urllib.parse import urlparse, urljoin, quote
from typing import Dict, List, Optional, Tuple

INFO = "cyan"
SUCCESS = "green"
WARNING = "yellow"
ERROR = "red"
HIGHLIGHT = "magenta"


class WAFDetector:
    def __init__(self, target: str):
        self.target = target.rstrip('/')
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate',
            'Connection': 'keep-alive',
            'Cache-Control': 'no-cache, no-store, must-revalidate',
            'Pragma': 'no-cache',
            'Expires': '0'
        })
        
        # ============================================================
        # ENHANCED WAF SIGNATURES (Headers + Cookies + Body)
        # ============================================================
        self.waf_signatures = {
            'Cloudflare': {
                'headers': ['cf-ray', 'cf-cache-status', 'cf-request-id', 'cf-ray-id', 'cf-worker'],
                'cookies': ['__cfduid', 'cf_clearance', '__cf_bm', 'cf_chl_prog', 'cf_chl_rc_ni'],
                'body': ['cloudflare-nginx', 'cloudflare ray', 'attention required', 'security challenge'],
                'status_codes': [403, 429, 503],
                'server': ['cloudflare']
            },
            'AWS WAF': {
                'headers': ['x-amzn-requestid', 'x-amzn-errortype', 'x-amz-cf-id', 'x-amzn-ErrorType'],
                'cookies': ['awsalb', 'awsalbcors', 'aws-waf-token'],
                'body': ['awswaf', 'request blocked', 'aws waf'],
                'status_codes': [403, 400],
                'server': []
            },
            'ModSecurity': {
                'headers': ['x-mod-security', 'mod_security', 'x-mods-events'],
                'cookies': [],
                'body': ['mod_security', 'modsecurity', 'on-site filtering', 'not acceptable'],
                'status_codes': [403, 406],
                'server': []
            },
            'Imperva / Incapsula': {
                'headers': ['x-iinfo', 'x-cdn', 'x-request-id', 'x-instart-request-id'],
                'cookies': ['incap_ses', 'visid_incap', '_incap_', 'incap_ses_'],
                'body': ['incapsula', 'incident_id', 'imperva', 'visid_incap'],
                'status_codes': [403, 404, 406],
                'server': []
            },
            'Sucuri': {
                'headers': ['x-sucuri-id', 'x-sucuri-cache', 'x-sucuri-block'],
                'cookies': [],
                'body': ['sucuri cloudproxy', 'access denied - sucuri', 'sucuri web site firewall'],
                'status_codes': [403, 503],
                'server': ['sucuri']
            },
            'Akamai': {
                'headers': ['x-akamai-transformed', 'akamai-gtm', 'x-akamai-request-id'],
                'cookies': ['ak_bmsc', 'bm_sz', 'akavpau', '_abck'],
                'body': ['akamai ghost', 'access denied akamai', 'akamai reference'],
                'status_codes': [403, 404],
                'server': ['akamai']
            },
            'F5 Big-IP': {
                'headers': ['x-cbi-node', 'x-wa-info', 'x-f5-request-id'],
                'cookies': ['bigipserver', 'f5_cspm', 'TSxxxxxx', 'ASINFO'],
                'body': ['f5 big-ip', 'request denied by f5', 'f5 appliance'],
                'status_codes': [403, 404],
                'server': ['big-ip']
            },
            'FortiGate': {
                'headers': ['x-fortigate-waf', 'x-fortinet-request-id'],
                'cookies': ['fortiwafsid', 'fgd_id'],
                'body': ['fortigate', 'fortiweb', 'fortinet'],
                'status_codes': [403, 404],
                'server': ['fortigate']
            },
            'Barracuda': {
                'headers': ['x-barracuda', 'cuda'],
                'cookies': [],
                'body': ['barracuda', 'barracuda web filter', 'access denied by barracuda'],
                'status_codes': [403, 404],
                'server': ['barracuda']
            },
            'WordFence': {
                'headers': [],
                'cookies': ['wf_log', 'wf_scan', 'wordfence'],
                'body': ['wordfence', 'blocked by wordfence', 'generated by wordfence'],
                'status_codes': [403, 503],
                'server': []
            },
            'StackPath': {
                'headers': ['x-stackpath', 'sp-request-id'],
                'cookies': ['sp_ses', 'sp_id'],
                'body': ['stackpath', 'stackpath cdn'],
                'status_codes': [403, 404],
                'server': ['stackpath']
            },
            'Fastly': {
                'headers': ['x-fastly', 'x-served-by', 'x-cache', 'x-cache-hits'],
                'cookies': ['fastly'],
                'body': ['fastly', 'fastly cdn'],
                'status_codes': [403, 503],
                'server': ['fastly']
            },
            'Varnish': {
                'headers': ['x-varnish', 'x-cache', 'via', 'x-varnish-cache'],
                'cookies': [],
                'body': ['varnish', 'varnish cache server'],
                'status_codes': [503],
                'server': ['varnish']
            },
            'Generic WAF': {
                'headers': [],
                'cookies': [],
                'body': ['access denied', 'forbidden', 'blocked', 'unauthorized', 'security policy'],
                'status_codes': [403, 406, 429, 503],
                'server': []
            }
        }
        
        # ============================================================
        # MULTI-VECTOR TEST PAYLOADS (SQLi, XSS, LFI, CMDi)
        # ============================================================
        self.test_payloads = [
            # SQL Injection
            ("/?id=1' OR '1'='1", "SQLi - Basic"),
            ("/?id=1' AND SLEEP(5)--", "SQLi - Time-based"),
            ("/?id=1' UNION SELECT NULL--", "SQLi - Union"),
            ("/?id=1' AND 1=1--", "SQLi - Boolean"),
            
            # XSS
            ("/?q=<script>alert(1)</script>", "XSS - Script Tag"),
            ("/?q=<img src=x onerror=alert(1)>", "XSS - Image Event"),
            ("/?q=<svg/onload=alert(1)>", "XSS - SVG Event"),
            ("/?q=javascript:alert(1)", "XSS - JS Protocol"),
            
            # LFI
            ("/?file=../../../../etc/passwd", "LFI - Path Traversal"),
            ("/?page=php://filter/convert.base64-encode/resource=index.php", "LFI - PHP Filter"),
            
            # Command Injection
            ("/?cmd=; id", "CMDi - Semicolon"),
            ("/?ip=| whoami", "CMDi - Pipe"),
            ("/?exec=&& uname -a", "CMDi - Double Ampersand"),
            
            # Path Traversal
            ("/?path=../windows/win.ini", "Path Traversal - Windows"),
        ]
        
        # ============================================================
        # CUSTOM ERROR PAGE INDICATORS
        # ============================================================
        self.custom_error_indicators = [
            '404 Not Found', 'Page Not Found', 'صفحة غير موجودة',
            'The requested URL was not found', 'No such file',
            'Something went wrong', 'Error occurred',
            'Oops', 'Sorry', 'Page does not exist'
        ]

    # ============================================================
    # CACHE BYPASS TECHNIQUES (اللمسة النهائية)
    # ============================================================
    
    def _add_cache_buster(self, url: str) -> str:
        """
        إضافة معامل عشوائي لتجاوز الـ Cache
        يضمن أن كل طلب يصل إلى الـ WAF مباشرة
        """
        # توليد معاملات عشوائية متعددة لتجاوز أنواع مختلفة من الـ Cache
        cache_busters = [
            f"&_={int(time.time() * 1000)}",           # Timestamp in milliseconds
            f"&nocache={random.randint(100000, 999999)}",  # Random number
            f"&rand={random.random()}",                # Random float
            f"&cb={random.randint(1, 999999)}",        # Cache buster
            f"&t={int(time.time())}",                  # Unix timestamp
            f"&v={random.randint(1, 999999)}",         # Version random
        ]
        
        # اختيار 2-3 معاملات عشوائية لتكون أكثر فعالية
        selected = random.sample(cache_busters, min(3, len(cache_busters)))
        
        # إضافة المعاملات للـ URL
        if '?' in url:
            return url + ''.join(selected)
        else:
            return url + '?' + selected[0].lstrip('&')
    
    def _build_test_url(self, payload: str) -> str:
        """
        بناء URL الاختبار مع تجاوز الـ Cache
        """
        # إضافة الـ payload
        test_url = self.target + payload
        
        # إضافة معاملات تجاوز الـ Cache
        test_url = self._add_cache_buster(test_url)
        
        return test_url

    def run(self, verbose: bool = False) -> Optional[str]:
        """Advanced WAF detection with cache bypass"""
        
        cprint("\n" + "="*70, HIGHLIGHT)
        cprint("[WAF DETECTOR] AlZill V6 Pro - Advanced WAF/IPS Detection", HIGHLIGHT, attrs=['bold'])
        cprint("="*70, HIGHLIGHT)
        cprint(f"[*] Target: {self.target}", INFO)
        cprint("[*] Vectors: Headers | Cookies | Response Body | Status Codes", "yellow")
        cprint("[*] Payloads: SQLi | XSS | LFI | CMDi | Path Traversal", "yellow")
        cprint("[*] Cache Bypass: Active (Random parameters + Timestamp)", "green")
        
        detected_wafs = set()
        baseline_response = None
        baseline_cookies = None
        baseline_text = None
        baseline_status = None
        
        try:
            # Step 1: Get baseline (normal request with cache bypass)
            baseline_url = self._add_cache_buster(self.target)
            cprint(f"[*] Getting baseline with cache bypass...", INFO)
            
            baseline_response = self.session.get(baseline_url, timeout=10)
            baseline_headers = baseline_response.headers
            baseline_cookies = self.session.cookies
            baseline_text = baseline_response.text
            baseline_status = baseline_response.status_code
            
            if verbose:
                cprint(f"    Baseline Status: {baseline_status}", INFO)
                cprint(f"    Baseline Length: {len(baseline_text)} bytes", INFO)
            
            # Step 2: Test with multiple payloads (each with cache bypass)
            for payload, payload_name in self.test_payloads:
                if verbose:
                    cprint(f"\n[*] Testing: {payload_name}", INFO)
                
                # Build URL with payload and cache buster
                test_url = self._build_test_url(payload)
                
                if verbose:
                    cprint(f"    URL: {test_url[:100]}...", INFO)
                
                try:
                    response = self.session.get(test_url, timeout=10)
                    response_headers = response.headers
                    response_cookies = self.session.cookies
                    response_text = response.text
                    response_status = response.status_code
                    
                    # ============================================
                    # 1. Check Headers
                    # ============================================
                    for waf_name, signatures in self.waf_signatures.items():
                        for header_sig in signatures['headers']:
                            if header_sig in str(response_headers).lower():
                                detected_wafs.add((waf_name, "Header Signature"))
                                if verbose:
                                    cprint(f"    [!] {waf_name} detected via header: {header_sig}", WARNING)
                    
                    # ============================================
                    # 2. Check Cookies (مهم جداً)
                    # ============================================
                    for waf_name, signatures in self.waf_signatures.items():
                        for cookie_sig in signatures['cookies']:
                            for cookie in response_cookies:
                                if cookie_sig in cookie.name.lower():
                                    detected_wafs.add((waf_name, f"Cookie Signature: {cookie.name}"))
                                    if verbose:
                                        cprint(f"    [!] {waf_name} detected via cookie: {cookie.name}", WARNING)
                    
                    # ============================================
                    # 3. Check Response Body
                    # ============================================
                    for waf_name, signatures in self.waf_signatures.items():
                        for body_sig in signatures['body']:
                            if body_sig in response_text.lower():
                                detected_wafs.add((waf_name, "Response Body Pattern"))
                                if verbose:
                                    cprint(f"    [!] {waf_name} detected via body: {body_sig}", WARNING)
                    
                    # ============================================
                    # 4. Check Status Code Anomalies
                    # ============================================
                    if response_status != baseline_status:
                        for waf_name, signatures in self.waf_signatures.items():
                            if response_status in signatures['status_codes']:
                                detected_wafs.add((waf_name, f"Status Code {response_status}"))
                                if verbose:
                                    cprint(f"    [!] {waf_name} detected via status code: {response_status}", WARNING)
                    
                    # ============================================
                    # 5. Check Server Header
                    # ============================================
                    server_header = response_headers.get('Server', '').lower()
                    for waf_name, signatures in self.waf_signatures.items():
                        for server_sig in signatures['server']:
                            if server_sig in server_header:
                                detected_wafs.add((waf_name, f"Server Header: {server_header}"))
                                if verbose:
                                    cprint(f"    [!] {waf_name} detected via server header: {server_header}", WARNING)
                    
                    # ============================================
                    # 6. Check for Custom Error Pages (Soft WAF)
                    # ============================================
                    if self._is_custom_error_page(response_text, baseline_text):
                        if verbose:
                            cprint(f"    [!] Custom error page detected (potential WAF)", WARNING)
                        detected_wafs.add(("Generic WAF (Custom Error Page)", "Custom Error Page"))
                    
                    # Small delay to avoid rate limiting
                    time.sleep(random.uniform(0.3, 0.8))
                    
                except requests.exceptions.Timeout:
                    if verbose:
                        cprint(f"    [!] Timeout on {payload_name} - Possible WAF blocking", WARNING)
                    detected_wafs.add(("Generic WAF (Timeout)", "Request Timeout"))
                except Exception as e:
                    if verbose:
                        cprint(f"    Error testing {payload_name}: {e}", WARNING)
            
            # Step 3: Analyze results
            return self._report_results(detected_wafs)
            
        except Exception as e:
            cprint(f"[!] WAF Detection failed: {e}", ERROR)
            return None

    def _is_custom_error_page(self, response_text: str, baseline_text: str) -> bool:
        """Check if response is a custom error page (Soft WAF)"""
        
        # Check for error indicators
        error_count = 0
        for indicator in self.custom_error_indicators:
            if indicator.lower() in response_text.lower():
                error_count += 1
        
        # If multiple error indicators found and content is significantly different
        if error_count >= 2:
            # Check if content length is significantly different
            if abs(len(response_text) - len(baseline_text)) < 500:
                return True
        
        return False

    def _report_results(self, detected_wafs: set) -> Optional[str]:
        """Report detection results"""
        
        cprint("\n" + "="*70, HIGHLIGHT)
        cprint("📊 WAF DETECTION RESULTS", HIGHLIGHT, attrs=['bold'])
        cprint("="*70, HIGHLIGHT)
        
        if detected_wafs:
            # Group by WAF name
            waf_counts = {}
            for waf_name, method in detected_wafs:
                if waf_name not in waf_counts:
                    waf_counts[waf_name] = []
                waf_counts[waf_name].append(method)
            
            cprint(f"\n[!!!] WAF DETECTED!", ERROR, attrs=['bold'])
            
            for waf_name, methods in waf_counts.items():
                cprint(f"\n  🔴 {waf_name}:", ERROR)
                for method in methods[:3]:  # Show up to 3 detection methods
                    cprint(f"     └─ Detected via: {method}", WARNING)
            
            # Return the most specific WAF name (longest string, likely most accurate)
            best_match = max(waf_counts.keys(), key=len)
            return best_match
        
        else:
            cprint(f"\n[✓] No WAF Detected", SUCCESS)
            cprint(f"    Target appears unprotected or using custom rules", INFO)
            return None


# ============================================================
# Legacy function for backward compatibility
# ============================================================

def detect_waf(target: str, verbose: bool = False) -> Optional[str]:
    """Legacy function"""
    detector = WAFDetector(target)
    return detector.run(verbose)


if __name__ == "__main__":
    import sys

# ============================================================
# Proxy Support (Auto-injected)
# ============================================================
def get_session_with_proxy(proxy_session=None):
    """Get requests session with proxy support"""
    if proxy_session:
        return proxy_session
    return requests.Session()


def request_with_retry(url, method='GET', data=None, json=None, headers=None, 
                       proxy_session=None, max_retries=3, delay=2, **kwargs):
    """Send request with automatic retry and proxy support"""
    session = get_session_with_proxy(proxy_session)
    
    for attempt in range(max_retries):
        try:
            if method.upper() == 'GET':
                response = session.get(url, headers=headers, timeout=10, verify=False, **kwargs)
            elif method.upper() == 'POST':
                response = session.post(url, data=data, json=json, headers=headers, 
                                       timeout=10, verify=False, **kwargs)
            else:
                response = session.request(method, url, headers=headers, 
                                          timeout=10, verify=False, **kwargs)
            return response
        except (requests.exceptions.ConnectionError, ConnectionResetError) as e:
            if attempt < max_retries - 1:
                time.sleep(delay)
            else:
                raise e
        except Exception as e:
            if attempt < max_retries - 1:
                time.sleep(delay)
            else:
                raise e
    return None

    
    if len(sys.argv) > 1:
        target = sys.argv[1]
        verbose = "--verbose" in sys.argv or "-v" in sys.argv
        detector = WAFDetector(target)
        result = detector.run(verbose)
        
        if result:
            cprint(f"\n[!] Final Result: {result}", ERROR, attrs=['bold'])
        else:
            cprint(f"\n[✓] Final Result: No WAF Detected", SUCCESS)
    else:
        print("Usage: python waf_detector.py <target_url> [--verbose]")
        print("Examples:")
        print("  python waf_detector.py https://example.com")
        print("  python waf_detector.py https://example.com --verbose")